version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongodb_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/teste_ixc
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
