version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge   # Alterado para bridge network

volumes:
  mongodb_data:
    driver: local
